---
name: Update Events and Deploy Site

on:
  schedule:
    - cron: "0 12 * * *"
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  update-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install npm dependencies
        run: npm install

      - name: Set up OCaml
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: "5.1.1"
          opam-repositories: |
            default: https://github.com/ocaml/opam-repository.git
            andresypopp: https://github.com/andreypopp/opam-repository.git

      - name: Install dependencies
        run: opam install . --deps-only --with-test

      - name: Run tests
        run: opam exec -- dune runtest

      - name: Fetch Data and Generate site
        run: |
          npm run bundle

      - name: Commit data and site & Push GH pages branch
        run: |
          git config user.name "Delhi Events Bot"
          git config user.email "punchagan+delhi-events@muse-amuse.in"
          git checkout gh-pages
          cp -a _build/default/dist/* .
          git add assets events.* index.html
          git commit -m "Update events data and site" || echo "No changes"
          git push origin gh-pages
